package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

const initTemplate = `# Antigravity Project Configuration
# Generated by: antigravity init
# Docs: https://antigravity.dev/docs/config

version: "1"

project:
  name: "my-project"
  slug: "my-project"
  repo: "https://github.com/your-user/my-project"

# ──────────────────────────────────────────────────────────────
# ENVIRONMENTS
# Define each environment with its branch, env vars, and CLI profiles.
# Antigravity will switch ALL of these with a single command.
# ──────────────────────────────────────────────────────────────
environments:
  development:
    branch: "develop"
    env:
      NODE_ENV: "development"
      DATABASE_URL: "postgresql://localhost:5432/myapp_dev"
      # Add your development environment variables here
    cli_profiles:
      - tool: "gh"
        account: "your-github-username"
      - tool: "aws"
        account: "dev-profile"
        region: "us-east-1"
      - tool: "supabase"
        account: "your-project-ref"
      - tool: "vercel"
        account: "my-project-dev"
        org: "your-team"

  staging:
    branch: "staging"
    env:
      NODE_ENV: "staging"
      DATABASE_URL: "postgresql://staging-host:5432/myapp_stg"
    cli_profiles:
      - tool: "gh"
        account: "your-github-username"
      - tool: "aws"
        account: "staging-profile"
        region: "us-east-1"
      - tool: "supabase"
        account: "your-staging-project-ref"

  production:
    branch: "main"
    env:
      NODE_ENV: "production"
      DATABASE_URL: "postgresql://prod-host:5432/myapp"
    cli_profiles:
      - tool: "aws"
        account: "production-profile"
        region: "us-east-1"
      - tool: "supabase"
        account: "your-production-project-ref"
      - tool: "vercel"
        account: "my-project-prod"
        org: "your-team"

# ──────────────────────────────────────────────────────────────
# SKILLS
# Control which automation skills run during a context switch.
# Lower priority numbers execute first.
# ──────────────────────────────────────────────────────────────
skills:
  - name: "context-injection"
    category: "context-injection"
    enabled: true
    priority: 1

  - name: "git-state"
    category: "git-state"
    enabled: true
    priority: 2

  - name: "cli-switching"
    category: "cli-switching"
    enabled: true
    priority: 3
`

func newInitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "📦 Initialize Antigravity in the current project",
		Long: `Creates an antigravity.yaml configuration file in the current directory
with a template structure for defining your project environments and CLI profiles.

Edit the generated file to match your project's accounts and credentials.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			configPath := filepath.Join(".", "antigravity.yaml")

			// Check if file already exists
			if _, err := os.Stat(configPath); err == nil {
				return fmt.Errorf("antigravity.yaml already exists in this directory. Use --force to overwrite")
			}

			// Write the template
			if err := os.WriteFile(configPath, []byte(initTemplate), 0644); err != nil {
				return fmt.Errorf("failed to write config file: %w", err)
			}

			fmt.Print(banner)
			fmt.Println("  ✅ \033[1;32mAntigravity initialized!\033[0m")
			fmt.Println()
			fmt.Println("  📄 Created: antigravity.yaml")
			fmt.Println()
			fmt.Println("  Next steps:")
			fmt.Println("  1. Edit antigravity.yaml with your project details")
			fmt.Println("  2. Configure your CLI profiles for each environment")
			fmt.Println("  3. Run: antigravity switch development")
			fmt.Println()

			// Also ensure the global config directory exists
			home, err := os.UserHomeDir()
			if err == nil {
				globalDir := filepath.Join(home, ".antigravity")
				os.MkdirAll(globalDir, 0700)
			}

			return nil
		},
	}

	return cmd
}
