service: nexus-backend-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  timeout: 30
  environment:
    # Estas variables deben existir en el entorno al momento del despliegue 
    # o puedes usar Parameter Store / Secrets Manager
    DATABASE_URL: ${env:DATABASE_URL, ''}
    ENVIRONMENT: production
  httpApi:
    cors: true

functions:
  api:
    handler: app.main.handler
    events:
      - httpApi:
          path: /
          method: '*'
      - httpApi:
          path: /{proxy+}
          method: '*'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true # Fuerza siempre el uso de Docker para compilar (incluso en GitHub Actions) para evitar error de GLIBC
    slim: true
